### ISSUE TITLE
repository-triggered builds

### ISSUE THREAD

**Issue by ehrenb** [ehrenb/machina#14]
When machina-base is built, also trigger subsequent builds of downstream images.

**Comment by ehrenb** [comment]
In machina-base, the following can be put into a worfklow to trigger a downstream build (of machina-zip, for example):

```yaml
       - name: Trigger Workflow
         uses: actions/github-script@v6
         with:
           github-token: ${{ secrets.PAT_TOKEN }}
           script: |
             github.rest.actions.createWorkflowDispatch({
               owner: 'ehrenb',
               repo: 'machina-zip',
               workflow_id: 'docker-image.yml',
               ref: 'main',
             })
```

This forces machina-zip to rebuild and push a new image tagged with 'main'.  This doesn't really help when a new release is cut, and we want to ensure the version-tagged image has the upstream machina-base:latest.
